import { ApiIndicador } from "../types/data";

export const indicadorInitialState: ApiIndicador = {
  version: "",
  autor: "",
  fecha: "",
  uf: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  ivp: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  dolar: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  dolar_intercambio: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  euro: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  ipc: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  utm: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  imacec: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  tpm: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  libra_cobre: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  tasa_desempleo: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
  bitcoin: {
    codigo: "",
    nombre: "",
    unidad_medida: "",
    fecha: "",
    valor: 0,
  },
};
